### ISSUE TITLE
Ability to execute JSON on data wout OpenRefine running?

### ISSUE THREAD

**Issue by heoa** [vpnagraj/rrefine#4]
This is not quite clear in docs but is it possible to use the extracted JSON from OpenRefine on data outside OpenRefine without having OpenRefine running?

I need this for Docker pipeline by which I want all uploaded files refined automatically after a push to the repo.   

_Sent from my Motorola Moto G (5) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by vpnagraj** [comment]
@heoa thanks for reaching out ... at present `rrefine` only works with a running `OpenRefine` session ... but your use-case is duly noted and i will keep this issue open as a feature request
