### ISSUE TITLE
refine_upload is not creating a new project with the data file

### ISSUE THREAD

**Issue by IEORTools** [vpnagraj/rrefine#5]
While using the rrefine vignette I was trying to upload a new data project to OpenRefine.  The following command does not seem create the new project with the vignette csv file.  I'm using R version 3.6, OpenRefine 3.4-beta2 on a Linux Ubuntu 18.04 system.

Problem R script line is follows
refine_upload(file = "lateformeeting.csv", project.name = "lfm_cleanup", open.browser = TRUE)

**Comment by vpnagraj** [comment]
@IEORTools thanks for raising this issue. 

it looks like OpenRefine began requiring a CSRF token for certain API requests.

i have a fix pushed up to a dev branch. i'll be merging it into master soon, and will eventually cut a new CRAN release.

for now you can try it out with the following:

```
# install.packages("devtools")
devtools::install_github(repo = "vpnagraj/rrefine", ref = "csrf-fix")
library(rrefine)

write.csv(lateformeeting, file = "lateformeeting.csv", row.names = FALSE)
refine_upload(file = "lateformeeting.csv", project.name = "lfm_cleanup", open.browser = TRUE)
```

i'm going to close this issue for now. feel free to re-open if you are still experiencing problems running the vignette examples.
